config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'posts#index'
  resources :posts, only: %i[index new create show] do
    resources :comments, only: %i[create]
    resources :likes, only: %i[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 50 }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User'
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :title, presence: true, length: { minimum: 5, maximum: 255 }
  validates :body, presence: true, length: { minimum: 200, maximum: 4000 }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_ancestry

  validates :content, presence: true, length: { minimum: 5, maximum: 200 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy, inverse_of: :creator, foreign_key: :creator_id
  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post_comment = @post.comments.build(comment_params)
    @post_comment.user = current_user

    if @post_comment.save
      flash[:notice] = t('comments.flash.notice')
    else
      flash[:alert] = t('comments.flash.alert')
    end

    redirect_to @post
  end

  private

  def comment_params
    params.required(:post_comment).permit(:content, :parent_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post

  def create
    @post.likes.find_or_create_by(user_id: current_user.id)

    redirect_to @post
  end

  def destroy
    @like = @post.likes.find_by(id: params[:id], user_id: current_user.id)
    @like&.destroy

    redirect_to @post
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = Post.includes(:category, :creator).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @new_post_comment = @post.comments.build
    @post_comments = @post.comments.arrange
    @post_likes_count = @post.likes.count
    @current_user_post_like = @post.likes.find_by(user_id: current_user.id) if current_user
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = t('posts.flash.notice')
      redirect_to @post
    else
      flash[:alert] = t('posts.flash.alert')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.required(:post).permit(:title, :body, :category_id)
  end
end

app/views/comments/_form.html.slim
= simple_form_for @new_post_comment, url: post_comments_path(@post, @new_post_comment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :content, label: false
  = f.hidden_field :parent_id, value: parent

  = f.button :submit, t('comments.form.leave_a_comment'), class: 'btn btn-primary mt-2'

app/views/comments/_index.html.slim
- post_comments.each do |comment, children|
  .card.mt-2.rounded-0 id = "comment-#{comment.id}"
    .card-header.border-0
      = link_to '#', "#comment-#{comment.id}", class: 'me-2'
      span.me-2
        = comment.user.email
      span.fs-6.text-muted
        = time_ago_in_words(comment.created_at)

    .card-body.border-0
      p.card-text
        = comment.content

    - if user_signed_in?
      .card-footer.border-0
        = link_to t('comments.index.reply'), '#', class: 'fs-6 text-decoration-underline text-lowercase collapsed',
                                type: 'button',
                                aria_exanded: 'false',
                                aria_controls: "response_comment-#{comment.id}",
                                'data-bs-target' => "#response_comment-#{comment.id}",
                                'data-bs-toggle' => 'collapse'

        .ms-2.collapse id="response_comment-#{comment.id}"
          = render 'comments/form', parent: comment.id

    - if children.any?
      .ms-4
        = render 'comments/index', post_comments: children

app/views/layouts/application.html.slim
doctype html
html
  head
    title RailsProject64
    meta name='viewport' content='width=device-width,initial-scale=1'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

  body.d-flex.flex-column.h-100
    .container.mb-2
      .d-flex.flex-wrap.align-items-center.py-2.border-bottom
        .navbar.navbar-expand-md.navbar-light.me-auto
          = link_to root_path
            = image_tag('https://upload.wikimedia.org/wikipedia/commons/2/25/Hexlet-logo.jpg', height: '30', width: '30')
        ul.nav.nav-pills
          - if user_signed_in?
            li.nav-item.me-2
              p.nav-link.disabled
                = current_user.email
            li.nav-item.me-2
              = link_to t('navbar.create_new_post'), new_post_path, class: 'nav-link link-dark'
            li.nav-item.me-2
            = link_to t('navbar.sign_out'), destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link link-dark'

          - else
            li.nav-item.me-2
              = link_to t('navbar.sign_in'), new_user_session_path, class: 'nav-link link-dark'
            li.nav-item.me-2
              = link_to t('navbar.sign_up'), new_user_registration_path, class: 'nav-link link-dark'

    .container.my-4
      - if flash[:notice]
        p.alert.alert-success role='alert'
          = notice

      - if flash[:alert]
        p.alert.alert-danger role='alert'
          = alert

      = yield

app/views/posts/_form.html.slim
= simple_form_for post do |f|
  = f.input :title
  = f.association :category
  = f.input :body

  = f.button :submit, class: 'btn btn-primary mt-3'

app/views/posts/_post.html.slim
.row
  .col-md-12
    .card.mb-3
      .card-body
        h2.h5.card-title
          = link_to post.title, post_path(post), class: 'link-dark text-decoration-none'
        .card-text.mb-2
          = truncate(post.body, length: 330)
        .text-righ.small.text-muted.mt-auto
          span.me-2
            = "#{t('posts.index.likes')}: #{post.likes.count}"
          span.me-2
            = time_ago_in_words(post.created_at)
          span
            = post.creator.email

app/views/posts/index.html.slim
h1 = t('posts.index.collective_blog')
- @posts.each do |post_elem|
  = render 'post', post: post_elem

app/views/posts/new.html.slim
h1 = t('posts.new.new_post')

= render 'form', post: @post

app/views/posts/show.html.slim
ol.breadcrumb
  li.breadcrumb-item
    = link_to t('posts.show.all_posts'), posts_path
  li.breadcrumb-item.active
    = @post.category.name
.row.justify-content-center.mt-4
  article.col-12
    h1.mb-4.mb-lg-5
      = @post.title
    p
      = @post.body

    .d-flex.justify-content-between.mt-5
      #post-section
        span.me-2
          = @post.creator.email
        span
          = time_ago_in_words(@post.created_at)

      #likes-section
        span.me-2
          = @post_likes_count

        - if current_user && @current_user_post_like
          = link_to post_like_path(@post, @current_user_post_like), data: { turbo_method: :delete }, class: 'link-dark'
            i.bi.bi-hand-thumbs-up-fill
        - elsif current_user
          = link_to post_likes_path(@post), data: { turbo_method: :post }, class: 'link-dark'
            i.bi.bi-hand-thumbs-up
        - else
          i.bi.bi-hand-thumbs-up

#comment-section.lead.mt-3
  span
    =t('posts.show.comments')
  - if user_signed_in?
    = render 'comments/form', parent: nil
  - if @post_comments
    = render 'comments/index', post_comments: @post_comments